#!/usr/bin/env simnibs_python
# -*- coding: utf-8 -*-

"""Create subject-space ROI masks from project-local MNI ROI templates."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from tit.paths import get_path_manager

ROI_TEMPLATE_DIRNAME = "rois"


@dataclass(frozen=True)
class SubjectROIResult:
    """Summary of one generated subject-space ROI mask."""

    subject_id: str
    source_path: Path
    path: Path
    voxel_count: int
    created: bool


def project_roi_template_dir(project_dir: str | Path) -> Path:
    """Return the project-local folder for MNI ROI templates."""
    return Path(project_dir) / "derivatives" / "ti-toolbox" / ROI_TEMPLATE_DIRNAME


def discover_mni_roi_templates(
    project_dir: str | Path,
    template_dir: str | Path | None = None,
) -> tuple[Path, ...]:
    """Return all local NIfTI ROI templates available for subject-space warping."""
    root = (
        Path(template_dir)
        if template_dir is not None
        else project_roi_template_dir(project_dir)
    )
    if not root.is_dir():
        return ()
    return tuple(
        sorted(
            path
            for path in root.rglob("*")
            if path.is_file() and path.name.endswith((".nii", ".nii.gz"))
        )
    )


def _subject_id(subject_id: str) -> str:
    return str(subject_id).strip().removeprefix("sub-")


def _strip_nifti_suffix(name: str) -> str:
    if name.endswith(".nii.gz"):
        return name[: -len(".nii.gz")]
    if name.endswith(".nii"):
        return name[: -len(".nii")]
    return name


def _strip_mni_suffix(name: str) -> str:
    for suffix in ("_MNI", "_mni", "-MNI", "-mni"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return name


def _subject_relative_path(
    template_root: Path, template_path: Path, subject_id: str
) -> Path:
    rel_parent = template_path.relative_to(template_root).parent
    parts = list(rel_parent.parts)
    if parts and parts[-1].lower().endswith("_mni"):
        parts[-1] = parts[-1][:-4]
    base = _strip_mni_suffix(_strip_nifti_suffix(template_path.name))
    return Path(*parts) / f"{base}_sub-{subject_id}.nii.gz"


def _sidecar_path(nii_path: Path) -> Path:
    return nii_path.with_name(nii_path.name.removesuffix(".nii.gz") + ".json")


def _template_sidecar_path(template_path: Path) -> Path:
    return template_path.with_name(_strip_nifti_suffix(template_path.name) + ".json")


def _load_template_metadata(template_path: Path) -> dict:
    sidecar = _template_sidecar_path(template_path)
    if not sidecar.exists():
        return {}
    with sidecar.open() as f:
        return json.load(f)


def _load_binary_mask(path: Path) -> tuple[np.ndarray, object]:
    import nibabel as nib

    img = nib.load(str(path))
    data = np.asanyarray(img.dataobj)
    return data > 0, img


def _save_binary_mask(
    mask: np.ndarray, reference_img: object, output_path: Path
) -> None:
    import nibabel as nib

    output_path.parent.mkdir(parents=True, exist_ok=True)
    header = reference_img.header.copy()
    header.set_data_dtype(np.uint8)
    img = nib.Nifti1Image(mask.astype(np.uint8), reference_img.affine, header)
    nib.save(img, str(output_path))


def _warp_volume(source: Path, m2m_dir: Path, output: Path, reference: Path) -> None:
    from simnibs.utils import transformations

    transformations.warp_volume(
        str(source),
        str(m2m_dir),
        str(output),
        transformation_direction="mni2subject",
        transformation_type="nonl",
        reference=str(reference),
        order=0,
        method="nearest",
        binary=True,
    )


def _write_sidecar(
    output_path: Path,
    *,
    subject_id: str,
    template_path: Path,
    template_root: Path,
    voxel_count: int,
    source_metadata: dict | None = None,
    m2m_dir: Path,
) -> None:
    source_metadata = source_metadata or {}
    payload = {
        "name": _strip_mni_suffix(_strip_nifti_suffix(template_path.name)),
        "space": f"sub-{subject_id} subject space",
        "source_space": source_metadata.get("space", "MNI"),
        "source_roi": str(template_path),
        "source_roi_relative": str(template_path.relative_to(template_root)),
        "labels": source_metadata.get("labels", []),
        "voxels_subject": int(voxel_count),
        "m2m_dir": str(m2m_dir),
        "note": (
            "Generated by TI-Toolbox from a project-local MNI ROI template "
            "using SimNIBS mni2subject warping."
        ),
    }
    _sidecar_path(output_path).write_text(json.dumps(payload, indent=2) + "\n")


def create_subject_space_rois(
    project_dir: str | Path,
    subject_id: str,
    *,
    template_dir: str | Path | None = None,
    output_dir: str | Path | None = None,
    overwrite: bool = False,
) -> list[SubjectROIResult]:
    """Warp all local MNI ROI templates into one subject's m2m space."""
    sid = _subject_id(subject_id)
    pm = get_path_manager(str(project_dir))
    m2m_dir = Path(pm.m2m(sid))
    t1_path = Path(pm.t1(sid))
    if not m2m_dir.is_dir():
        raise FileNotFoundError(f"Missing m2m folder for sub-{sid}: {m2m_dir}")
    if not t1_path.exists():
        raise FileNotFoundError(
            f"Missing SimNIBS T1 reference for sub-{sid}: {t1_path}"
        )

    root = (
        Path(template_dir)
        if template_dir is not None
        else project_roi_template_dir(project_dir)
    )
    templates = discover_mni_roi_templates(project_dir, root)
    if not templates:
        raise FileNotFoundError(
            "No MNI ROI templates were found. Place .nii or .nii.gz masks in "
            f"{root}"
        )

    roi_dir = Path(output_dir) if output_dir else Path(pm.rois(sid))
    results: list[SubjectROIResult] = []

    for template_path in templates:
        output = roi_dir / _subject_relative_path(root, template_path, sid)
        created = overwrite or not output.exists()
        if created:
            output.parent.mkdir(parents=True, exist_ok=True)
            _warp_volume(template_path, m2m_dir, output, t1_path)
            mask, img = _load_binary_mask(output)
            _save_binary_mask(mask, img, output)
            _write_sidecar(
                output,
                subject_id=sid,
                template_path=template_path,
                template_root=root,
                voxel_count=int(mask.sum()),
                source_metadata=_load_template_metadata(template_path),
                m2m_dir=m2m_dir,
            )
        else:
            mask, _img = _load_binary_mask(output)

        results.append(
            SubjectROIResult(
                subject_id=sid,
                source_path=template_path,
                path=output,
                voxel_count=int(mask.sum()),
                created=created,
            )
        )

    return results
